//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaWeather.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaWeather.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia (NH₃).
        /// </summary>
        public static string AirPollution_Ammonia_Label {
            get {
                return ResourceManager.GetString("AirPollution_Ammonia_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Index (AQI).
        /// </summary>
        public static string AirPollution_AQI_Label {
            get {
                return ResourceManager.GetString("AirPollution_AQI_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AQI.
        /// </summary>
        public static string AirPollution_AQI_Short {
            get {
                return ResourceManager.GetString("AirPollution_AQI_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon Monoxide (CO).
        /// </summary>
        public static string AirPollution_CarbonMonoxide_Label {
            get {
                return ResourceManager.GetString("AirPollution_CarbonMonoxide_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen Dioxide (NO₂).
        /// </summary>
        public static string AirPollution_NitrogenDioxide_Label {
            get {
                return ResourceManager.GetString("AirPollution_NitrogenDioxide_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozone (O₃).
        /// </summary>
        public static string AirPollution_Ozone_Label {
            get {
                return ResourceManager.GetString("AirPollution_Ozone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O₃.
        /// </summary>
        public static string AirPollution_Ozone_Short {
            get {
                return ResourceManager.GetString("AirPollution_Ozone_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM10 (Coarse Dust).
        /// </summary>
        public static string AirPollution_PM10_Label {
            get {
                return ResourceManager.GetString("AirPollution_PM10_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM2.5 (Fine Dust).
        /// </summary>
        public static string AirPollution_PM25_Label {
            get {
                return ResourceManager.GetString("AirPollution_PM25_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM2.5.
        /// </summary>
        public static string AirPollution_PM25_Short {
            get {
                return ResourceManager.GetString("AirPollution_PM25_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudiness.
        /// </summary>
        public static string CurrentWeather_Cloudiness_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Cloudiness_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like:.
        /// </summary>
        public static string CurrentWeather_FeelsLike_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_FeelsLike_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string CurrentWeather_Humidity_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Humidity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string CurrentWeather_Precipitation_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Precipitation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Pressure.
        /// </summary>
        public static string CurrentWeather_Pressure_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Pressure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string CurrentWeather_Visibility_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Visibility_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string CurrentWeather_Wind_Label {
            get {
                return ResourceManager.GetString("CurrentWeather_Wind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR POLLUTION FORECAST.
        /// </summary>
        public static string MainWindow_AirPollutionForecast_TabItemHeader {
            get {
                return ResourceManager.GetString("MainWindow_AirPollutionForecast_TabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWeatherMap API Key.
        /// </summary>
        public static string MainWindow_ApiKey_Header {
            get {
                return ResourceManager.GetString("MainWindow_ApiKey_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string MainWindow_ApiKey_Placeholder {
            get {
                return ResourceManager.GetString("MainWindow_ApiKey_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the City.
        /// </summary>
        public static string MainWindow_City_Header {
            get {
                return ResourceManager.GetString("MainWindow_City_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string MainWindow_City_Placeholder {
            get {
                return ResourceManager.GetString("MainWindow_City_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT AIR POLLUTION.
        /// </summary>
        public static string MainWindow_CurrentAirPollution_TabItemHeader {
            get {
                return ResourceManager.GetString("MainWindow_CurrentAirPollution_TabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT WEATHER.
        /// </summary>
        public static string MainWindow_CurrentWeather_TabItemHeader {
            get {
                return ResourceManager.GetString("MainWindow_CurrentWeather_TabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_Error_Title {
            get {
                return ResourceManager.GetString("MainWindow_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Weather.
        /// </summary>
        public static string MainWindow_GetWeather_Button {
            get {
                return ResourceManager.GetString("MainWindow_GetWeather_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainWindow_Language_Header {
            get {
                return ResourceManager.GetString("MainWindow_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading weather data....
        /// </summary>
        public static string MainWindow_Loading_Message {
            get {
                return ResourceManager.GetString("MainWindow_Loading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvaloniaWeather - Weather Forecast.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string MainWindow_Unit_Header {
            get {
                return ResourceManager.GetString("MainWindow_Unit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER FORECAST.
        /// </summary>
        public static string MainWindow_WeatherForecast_TabItemHeader {
            get {
                return ResourceManager.GetString("MainWindow_WeatherForecast_TabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured at: {0:dd.MM.yyyy HH:mm}.
        /// </summary>
        public static string MeasuredAt_Label {
            get {
                return ResourceManager.GetString("MeasuredAt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city &apos;{0}&apos; was not found. Please check the spelling..
        /// </summary>
        public static string WeatherService_Exception_CityNotFound {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name cannot be null or empty..
        /// </summary>
        public static string WeatherService_Exception_CityNull {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving weather data. Please try again..
        /// </summary>
        public static string WeatherService_Exception_CurrentWeather {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving geolocation data. Please check your API key..
        /// </summary>
        public static string WeatherService_Exception_Geolocation {
            get {
                return ResourceManager.GetString("WeatherService_Exception_Geolocation", resourceCulture);
            }
        }
    }
}
