//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaWeather.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaWeather.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenWeatherMap API Key.
        /// </summary>
        public static string MainWindow_ApiKey_Header {
            get {
                return ResourceManager.GetString("MainWindow_ApiKey_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string MainWindow_ApiKey_Placeholder {
            get {
                return ResourceManager.GetString("MainWindow_ApiKey_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the City.
        /// </summary>
        public static string MainWindow_City_Header {
            get {
                return ResourceManager.GetString("MainWindow_City_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string MainWindow_City_Placeholder {
            get {
                return ResourceManager.GetString("MainWindow_City_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Weather.
        /// </summary>
        public static string MainWindow_GetWeather_Button {
            get {
                return ResourceManager.GetString("MainWindow_GetWeather_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainWindow_Language_Header {
            get {
                return ResourceManager.GetString("MainWindow_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvaloniaWeather - Weather Forecast.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string MainWindow_Unit_Header {
            get {
                return ResourceManager.GetString("MainWindow_Unit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city &apos;{city}&apos; was not found. Please check the spelling..
        /// </summary>
        public static string WeatherService_Exception_CityNotFound {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name cannot be null or empty..
        /// </summary>
        public static string WeatherService_Exception_CityNull {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving weather data. Please try again..
        /// </summary>
        public static string WeatherService_Exception_CurrentWeather {
            get {
                return ResourceManager.GetString("WeatherService_Exception_CurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving geolocation data. Please check your API key..
        /// </summary>
        public static string WeatherService_Exception_Geolocation {
            get {
                return ResourceManager.GetString("WeatherService_Exception_Geolocation", resourceCulture);
            }
        }
    }
}
